@startuml

skinparam classAttributeIconSize 0

interface BleakwindBuffet.Data.IOrderItem {
	{abstract} Price : double <<get>>
	{abstract} Calories : uint <<get>>
	{abstract} SpecialInstructions : System.Collections.Generic.List<string> <<get>>
}

class BleakwindBuffet.Data.Menu <<static>> {
	- {static} <<readonly>> sizes : BleakwindBuffet.Data.Enums.Size[]
	+ Entrees() : System.Collections.Generic.IEnumerable<BleakwindBuffet.Data.IOrderItem>
	+ Sides() : System.Collections.Generic.IEnumerable<BleakwindBuffet.Data.IOrderItem>
	+ Drinks() : System.Collections.Generic.IEnumerable<BleakwindBuffet.Data.IOrderItem>
	+ FullMenu() : System.Collections.Generic.IEnumerable<BleakwindBuffet.Data.IOrderItem>
}
BleakwindBuffet.Data.Menu "1" o-- "0..*" BleakwindBuffet.Data.IOrderItem

class BleakwindBuffet.Data.Sides.DragonbornWaffleFries {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Sides.DragonbornWaffleFries
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Sides.DragonbornWaffleFries
BleakwindBuffet.Data.Sides.Side <|-- BleakwindBuffet.Data.Sides.DragonbornWaffleFries

class BleakwindBuffet.Data.Sides.FriedMiraak {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Sides.FriedMiraak
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Sides.FriedMiraak
BleakwindBuffet.Data.Sides.Side <|-- BleakwindBuffet.Data.Sides.FriedMiraak

class BleakwindBuffet.Data.Sides.MadOtarGrits {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Sides.MadOtarGrits
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Sides.MadOtarGrits
BleakwindBuffet.Data.Sides.Side <|-- BleakwindBuffet.Data.Sides.MadOtarGrits

abstract class BleakwindBuffet.Data.Sides.Side {
	+ {abstract} Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ {abstract} Price : double <<get>>
	+ {abstract} Calories : uint <<get>>
	+ {abstract} SpecialInstructions : System.Collections.Generic.List<string> <<get>>
}

class BleakwindBuffet.Data.Sides.VokunSalad {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Sides.VokunSalad
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Sides.VokunSalad
BleakwindBuffet.Data.Sides.Side <|-- BleakwindBuffet.Data.Sides.VokunSalad

enum BleakwindBuffet.Data.Enums.Size {
	Small
	Medium
	Large
}

enum BleakwindBuffet.Data.Enums.SodaFlavor {
	Blackberry
	Cherry
	Grapefruit
	Lemon
	Peach
	Watermelon
}

class BleakwindBuffet.Data.Entrees.BriarheartBurger {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- bun : bool
	- ketchup : bool
	- mustard : bool
	- pickle : bool
	- cheese : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Bun : bool <<get>> <<set>>
	+ Ketchup : bool <<get>> <<set>>
	+ Mustard : bool <<get>> <<set>>
	+ Pickle : bool <<get>> <<set>>
	+ Cheese : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.BriarheartBurger
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.BriarheartBurger
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.BriarheartBurger

class BleakwindBuffet.Data.Entrees.DoubleDraugr {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- bun : bool
	- ketchup : bool
	- mustard : bool
	- pickle : bool
	- cheese : bool
	- tomato : bool
	- lettuce : bool
	- mayo : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Bun : bool <<get>> <<set>>
	+ Ketchup : bool <<get>> <<set>>
	+ Mustard : bool <<get>> <<set>>
	+ Pickle : bool <<get>> <<set>>
	+ Cheese : bool <<get>> <<set>>
	+ Tomato : bool <<get>> <<set>>
	+ Lettuce : bool <<get>> <<set>>
	+ Mayo : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.DoubleDraugr
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.DoubleDraugr
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.DoubleDraugr

abstract class BleakwindBuffet.Data.Entrees.Entree {
	+ {abstract} Price : double <<get>>
	+ {abstract} Calories : uint <<get>>
	+ {abstract} SpecialInstructions : System.Collections.Generic.List<string> <<get>>
}

class BleakwindBuffet.Data.Entrees.GardenOrcOmelette {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- broccoli : bool
	- mushrooms : bool
	- tomato : bool
	- cheddar : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Broccoli : bool <<get>> <<set>>
	+ Mushrooms : bool <<get>> <<set>>
	+ Tomato : bool <<get>> <<set>>
	+ Cheddar : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.GardenOrcOmelette
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.GardenOrcOmelette
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.GardenOrcOmelette

class BleakwindBuffet.Data.Entrees.PhillyPoacher {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- sirloin : bool
	- onion : bool
	- roll : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Sirloin : bool <<get>> <<set>>
	+ Onion : bool <<get>> <<set>>
	+ Roll : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.PhillyPoacher
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.PhillyPoacher
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.PhillyPoacher

class BleakwindBuffet.Data.Entrees.SmokehouseSkeleton {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- sausageLink : bool
	- egg : bool
	- hashBrowns : bool
	- pancake : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ SausageLink : bool <<get>> <<set>>
	+ Egg : bool <<get>> <<set>>
	+ HashBrowns : bool <<get>> <<set>>
	+ Pancake : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.SmokehouseSkeleton
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.SmokehouseSkeleton
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.SmokehouseSkeleton

class BleakwindBuffet.Data.Entrees.ThalmorTriple {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- bun : bool
	- ketchup : bool
	- mustard : bool
	- pickle : bool
	- cheese : bool
	- tomato : bool
	- lettuce : bool
	- mayo : bool
	- bacon : bool
	- egg : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Bun : bool <<get>> <<set>>
	+ Ketchup : bool <<get>> <<set>>
	+ Mustard : bool <<get>> <<set>>
	+ Pickle : bool <<get>> <<set>>
	+ Cheese : bool <<get>> <<set>>
	+ Tomato : bool <<get>> <<set>>
	+ Lettuce : bool <<get>> <<set>>
	+ Mayo : bool <<get>> <<set>>
	+ Bacon : bool <<get>> <<set>>
	+ Egg : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.ThalmorTriple
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.ThalmorTriple
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.ThalmorTriple

class BleakwindBuffet.Data.Entrees.ThugsTBone {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Entrees.ThugsTBone
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Entrees.ThugsTBone
BleakwindBuffet.Data.Entrees.Entree <|-- BleakwindBuffet.Data.Entrees.ThugsTBone

class BleakwindBuffet.Data.Drinks.AretinoAppleJuice {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	- ice : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Ice : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Drinks.AretinoAppleJuice
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Drinks.AretinoAppleJuice
BleakwindBuffet.Data.Drinks.Drink <|-- BleakwindBuffet.Data.Drinks.AretinoAppleJuice

class BleakwindBuffet.Data.Drinks.CandlehearthCoffee {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	- ice : bool
	- roomForCream : bool
	- decaf : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Ice : bool <<get>> <<set>>
	+ RoomForCream : bool <<get>> <<set>>
	+ Decaf : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Drinks.CandlehearthCoffee
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Drinks.CandlehearthCoffee
BleakwindBuffet.Data.Drinks.Drink <|-- BleakwindBuffet.Data.Drinks.CandlehearthCoffee

abstract class BleakwindBuffet.Data.Drinks.Drink {
	+ {abstract} Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ {abstract} Price : double <<get>>
	+ {abstract} Calories : uint <<get>>
	+ {abstract} SpecialInstructions : System.Collections.Generic.List<string> <<get>>
}

class BleakwindBuffet.Data.Drinks.MarkarthMilk {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	- ice : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Ice : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Drinks.MarkarthMilk
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Drinks.MarkarthMilk
BleakwindBuffet.Data.Drinks.Drink <|-- BleakwindBuffet.Data.Drinks.MarkarthMilk

class BleakwindBuffet.Data.Drinks.SailorSoda {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	- ice : bool
	- flavor : BleakwindBuffet.Data.Enums.SodaFlavor
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Ice : bool <<get>> <<set>>
	+ Flavor : BleakwindBuffet.Data.Enums.SodaFlavor <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Drinks.SailorSoda
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Drinks.SailorSoda
BleakwindBuffet.Data.Drinks.Drink <|-- BleakwindBuffet.Data.Drinks.SailorSoda

class BleakwindBuffet.Data.Drinks.WarriorWater {
	+ <<event>> PropertyChanged : PropertyChangedEventHandler
	- size : BleakwindBuffet.Data.Enums.Size
	- ice : bool
	- lemon : bool
	+ <<override>> Price : double <<get>>
	+ <<override>> Calories : uint <<get>>
	+ <<override>> Size : BleakwindBuffet.Data.Enums.Size <<get>> <<set>>
	+ <<override>> SpecialInstructions : System.Collections.Generic.List<string> <<get>>
	+ Ice : bool <<get>> <<set>>
	+ Lemon : bool <<get>> <<set>>
	+ <<override>> ToString() : string
}
BleakwindBuffet.Data.IOrderItem <|.. BleakwindBuffet.Data.Drinks.WarriorWater
System.ComponentModel.INotifyPropertyChanged <|.. BleakwindBuffet.Data.Drinks.WarriorWater
BleakwindBuffet.Data.Drinks.Drink <|-- BleakwindBuffet.Data.Drinks.WarriorWater






class BleakwindBuffet.PointOfSale.App {
	- _contentLoaded : bool
	+ InitializeComponent() : void
	+ Main() : void
}

class BleakwindBuffet.PointOfSale.MainWindow {
	- MenuItems : System.Windows.Controls.ListBox
	- Add : System.Windows.Controls.Button
	- ProcessPayment : System.Windows.Controls.Button
	- CancelOrder : System.Windows.Controls.Button
	- CustomizationControl : System.Windows.Controls.Border
	- Subtotal : System.Windows.Controls.Label
	- Tax : System.Windows.Controls.Label
	- Total : System.Windows.Controls.Label
	- OrderContents : System.Windows.Controls.ListBox
	- _contentLoaded : bool
	- MenuItems_SelectionChanged(sender : object, e : System.Windows.Controls.SelectionChangedEventArgs) : void
	+ InitializeComponent() : void
}

class BleakwindBuffet.PointOfSale.MenuItemControl {
	- _contentLoaded : bool
	+ CustomizationControl: Type
	+ MenuItem: Type
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.MenuItemControl

class BleakwindBuffet.PointOfSale.Sides.DragonbornWaffleFriesControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Sides.DragonbornWaffleFriesControl
BleakwindBuffet.PointOfSale.Sides.DragonbornWaffleFriesControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Sides.FriedMiraakControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Sides.FriedMiraakControl
BleakwindBuffet.PointOfSale.Sides.FriedMiraakControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Sides.MadOtarGritsControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Sides.MadOtarGritsControl
BleakwindBuffet.PointOfSale.Sides.MadOtarGritsControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Sides.VokunSaladControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Sides.VokunSaladControl
BleakwindBuffet.PointOfSale.Sides.VokunSaladControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl




class BleakwindBuffet.PointOfSale.Enums.SizeControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}

class BleakwindBuffet.PointOfSale.Enums.SodaFlavorControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}




class BleakwindBuffet.PointOfSale.Entrees.BriarheartBurgerControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.BriarheartBurgerControl

class BleakwindBuffet.PointOfSale.Entrees.DoubleDraugrControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.DoubleDraugrControl

class BleakwindBuffet.PointOfSale.Entrees.GardenOrcOmeletteControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.GardenOrcOmeletteControl

class BleakwindBuffet.PointOfSale.Entrees.PhillyPoacherControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.PhillyPoacherControl

class BleakwindBuffet.PointOfSale.Entrees.SmokehouseSkeletonControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.SmokehouseSkeletonControl

class BleakwindBuffet.PointOfSale.Entrees.ThalmorTripleControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.ThalmorTripleControl

class BleakwindBuffet.PointOfSale.Entrees.ThugsTBoneControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Entrees.ThugsTBoneControl




class BleakwindBuffet.PointOfSale.Drinks.AretinoAppleJuiceControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Drinks.AretinoAppleJuiceControl
BleakwindBuffet.PointOfSale.Drinks.AretinoAppleJuiceControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Drinks.CandlehearthCoffeeControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Drinks.CandlehearthCoffeeControl
BleakwindBuffet.PointOfSale.Drinks.CandlehearthCoffeeControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Drinks.MarkarthMilkControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Drinks.MarkarthMilkControl
BleakwindBuffet.PointOfSale.Drinks.MarkarthMilkControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

class BleakwindBuffet.PointOfSale.Drinks.SailorSodaControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Drinks.SailorSodaControl
BleakwindBuffet.PointOfSale.Drinks.SailorSodaControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl
BleakwindBuffet.PointOfSale.Drinks.SailorSodaControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SodaFlavorControl

class BleakwindBuffet.PointOfSale.Drinks.WarriorWaterControl {
	- _contentLoaded : bool
	+ InitializeComponent() : void
}
BleakwindBuffet.PointOfSale.MainWindow "1" *-- "0..1" BleakwindBuffet.PointOfSale.Drinks.WarriorWaterControl
BleakwindBuffet.PointOfSale.Drinks.WarriorWaterControl "1" *-- "1" BleakwindBuffet.PointOfSale.Enums.SizeControl

@enduml
